language: node_js
node_js:
  - '0.10'
script: npm run lint
after_success: npm run deploy
env:
  global:
    - GH_REF: github.com/spbd/dashboard.git
    - secure: XyEVJFGvsoLnSUkjNnfp/sSlpUInnLila0JrJ3pBGth1M45kOtMLRHHpJTxkoQy4ZBEMdr/bqRH5dlXxBXXpINxqLSxakXR/xzjM2aVPJxIsWFwSajqe1n/0iAYkz0ZjL2+9nreDNYwOHMKU/XFWivTTD1J5p1sWnJQwvUeaHdY=
